### ISSUE TITLE
Javascript/PlaceholderAPI conditions

### ISSUE THREAD

**Issue by BiGUNMAN** [lucko/ConditionalPerms#1]
The current conditions are awesome, but it would be even better if you supported conditions that one could take from PlaceholderAPI. An example of what I imply would be the following:

http://pastebin.com/Q6xXmCbN

I don't know exactly how you would implement this, maybe separate nodes, or putting each expression in a separate file that you then refer to with a permission node like: cperms.expression.prison_level1 to indicate that expression. Anyways, I just thought it would expand the usefulness of the plugin. I would personally use it, I thought of it while looking at the LuckPerms documentation on default-assignments. :)

**Comment by lucko** [comment]
Sure. 

So the placeholder just returns a list of permission nodes?

**Comment by BiGUNMAN** [comment]
I don't really understand your question. If the conditions (expression) is true, then the player would have the permissions nodes under "true" applied to him, if it were false, a player would have other permission nodes applied.

**Comment by lucko** [comment]
So the config example you linked would be a part of ConditionalPerms? I just assumed it was already a feature of PlaceholderAPI.

**Comment by BiGUNMAN** [comment]
I'm suggesting the idea of these conditions people can create (the
conditions described above, with the help of placeholder api). I don't know
how exactly you'd want to implement it, but yes, I was thinking it would be
part of conditional perms.

**Comment by lucko** [comment]
Alright. LuckPerms is my priority right now, but I might get a chance to do this at some point. 🙂
