### ISSUE TITLE
AcidIsland and ASkyblock

### ISSUE THREAD

**Issue by crux22** [lucko/ConditionalPerms#3]
Conditions for AcidIsland & ASkyblock
https://www.spigotmc.org/resources/acidisland.581/

=]

**Comment by netherstar** [comment]
Vote. Please add it.

**Comment by Wqrld** [comment]
+ even if it is just "isonisland" 👍

**Comment by GriffinCodes** [comment]
I have added three ASkyBlock & AcidIsland conditions in #11 
- `<acidisland|askyblock>_in_island`
- `<acidisland|askyblock>_in_own_island`
- `<acidisland|askyblock>_is_island_member`

if there's any other specific conditions you'd like, I can PR them as well
