### ISSUE TITLE
Residence

### ISSUE THREAD

**Issue by chillerkraft** [lucko/ConditionalPerms#4]
Would it be possible to add residence support (free version on there plugin description) where i can somehow choose a specific area where certain perms are allowed?
Thanks

**Comment by lucko** [comment]
PR it.

**Comment by chillerkraft** [comment]
https://www.spigotmc.org/resources/residence-1-7-10-up-to-1-12.11480/
http://ltcraft.lt/Residence/

**Comment by lucko** [comment]
Yes, create a pull request.

**Comment by chillerkraft** [comment]
i don't know what to do after i click New Pull Request

**Comment by lucko** [comment]
Write the code which adds the hook, and then pull request your changes back into this repo.

I don't have time to add new conditions myself, as my time is occupied maintaining my other projects.

**Comment by chillerkraft** [comment]
oh alright maybe someone else who knows how to do that can do it for me
thanks anyways.
