### ISSUE TITLE
CombatTagPlus Condition Issue

### ISSUE THREAD

**Issue by Spazzinq** [lucko/ConditionalPerms#5]
I have been using CombatTagPlus 1.2.3 , PermissionsEx , and ConditionalPerms 1.3 and I realized that the CombatTagPlus conditions weren't working. Specifically, this was the permissions I used to test if it was working or not (cperms.!in_combat=noflyzone.autofly.all) . 
The NoFlyZone noflyzone.autofly.all permissions works so that it enables auto fly in specific regions.  I tested to make sure the issue wasn't the permission system/NoFlyZone plugin, by giving the user the normal noflyzone.autofly.all permission. They were able to automatically fly. This brings me to my conclusion that there is an issue with the condition between CombatTagPlus and ConditionalPerms.

--
~ Spazzinq

**Comment by lucko** [comment]
The node should be "cperms.!in_combat.noflyzone.autofly.all"

**Comment by Spazzinq** [comment]
Thank you so much :D I'll test it out later
