### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by Spazzinq** [lucko/ConditionalPerms#7]
Not sure what happened, but I got this error https://gist.github.com/Spazzinq/812429bbe413700416f2b363ec0a29fd

**Comment by lucko** [comment]
Should be fixed by

587e2598f93a02857928ab2a9758921c83fdfbe1

https://ci.lucko.me/job/ConditionalPerms/8/

**Comment by Spazzinq** [comment]
Just noting the build failed

**Comment by lucko** [comment]
Ok, I'm away atm, so will sort it when I get back.

**Comment by Spazzinq** [comment]
Leavin' me hangin'? :)

**Comment by lucko** [comment]
Sorry for the delay.

https://github.com/lucko/ConditionalPerms/commit/f758fde5537bfa97a7c3c1a8abd010f456adffb4
