### ISSUE TITLE
Region checks are not working (at least for me)

### ISSUE THREAD

**Issue by bendison** [lucko/ConditionalPerms#8]
Hello,

I've been trying to get region conditions to work without much luck. I ran this command:
`/lp user <player> permission set cperms.in_region=spawn.essentials.give true`

In my log file I receive the following response:
`17.11 01:18:18 [Server] INFO [DEBUG] Processing conditional permission: cperms.in_region=spawn.essentials.give
17.11 01:18:18 [Server] INFO [DEBUG] Found parameter: spawn
17.11 01:18:18 [Server] INFO [DEBUG] Found condition IN_REGION.
17.11 01:18:18 [Server] INFO [DEBUG] Player did not meet the conditions required for this permission to be applied.`

This region is the only one and there are no others overlapping. The only other region would be __global__ however I don't think that should cause this issue. I'm on WorldGuard version 6.2.1 at the moment with the latest version of ConditionalPerms. Let me know if you need any other information.

**Comment by lucko** [comment]
Not sure why that'd be -- my suggestion though is to use ExtraContexts instead.

https://ci.lucko.me/job/ExtraContexts/

Just install that to your plugins dir, and use `/lp user <player> permission set essentials.give true wg-region=spawn`
